### ISSUE TITLE
Segmentation fault out-of-box on M1 Mac

### ISSUE THREAD

**Issue by gabegrand** [Bam4d/Griddly#286]
Hi @Bam4d -- what is the current status of Apple Silicon support? I'm getting a seg fault out-of-box on my M1 Mac when trying to run a hello world example.

## Steps to reproduce
1. Install via conda and pip
```
conda create --name griddly python=3.7
conda activate griddly
pip install griddly
```

2. Run the following in a Python script
```
import gym
import griddly

if __name__ == '__main__':

    env = gym.make('GDY-Sokoban-v0')
    env.reset()
```

3. Encounter seg fault
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    player_observer_type=griddly.ObserverType.VECTOR,
AttributeError: module 'griddly' has no attribute 'ObserverType'
(griddly) grandg@dhcp-10-29-7-16 griddly % python test.py
/opt/anaconda3/envs/griddly/lib/python3.7/site-packages/gym/utils/passive_env_checker.py:32: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: ()
  "A Box observation space has an unconventional shape (neither an image, nor a 1D vector). "
/opt/anaconda3/envs/griddly/lib/python3.7/site-packages/gym/utils/passive_env_checker.py:175: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  "Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator."
/opt/anaconda3/envs/griddly/lib/python3.7/site-packages/gym/utils/passive_env_checker.py:188: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  "Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information."
zsh: segmentation fault
```

## Hardware
- M1 MacBook Pro (2021)
- macOS Monterey 12.3.1

## Other notes
Note that this is different than https://github.com/Bam4d/Griddly/issues/118 in that there now appears to be a build on PyPI that does satisfy an M1 Mac system's specs.

I tried building Griddly locally on my machine but encountered a different error with the provided commands
```
# Download the build requirements
> ./configure.sh -p=WASM -b=Debug

conan install: error: unrecognized arguments: -if build_wasm
```

Please let me know if there's anything else I should test out -- I'd really like to use Griddly for a future project!

**Comment by Bam4d** [comment]
There's not out-of-the-box support for m1/m2 yet but we've just overhauled the building process to use github actions so I'm hoping its possible to do something in the new build pipeline.

In the meantime, you should be able to install from source on m1/m2 macs.

The error you see:
`conan install: error: unrecognized arguments: -if build_wasm`

Can be resolved if you specifically use version `1.59.0` of conan and not `2.X.X`

**Comment by Bam4d** [comment]
also you should fix this error first: AttributeError: module 'griddly' has no attribute 'ObserverType' 

I think you need to do

```
from griddly import gd
```

and then use:
```
gd.ObserverType.VECTOR
```

**Comment by gabegrand** [comment]
Thanks so much. I went ahead and tried to build the binaries from scratch. I was able to complete the build, but still unable to run a hello world script due to some Vulkan error:

```
[2023-07-12 12:13:04.984] [error] BAD VK Result-3
Assertion failed: (("Vulkan command did not execute correctly", res == VK_SUCCESS)), function vk_check, file VulkanUtil.hpp, line 14.
```

Here's the "execution trace" of my process:

### Building the binaries
- I downgraded `conan` as you instructed and the `configure.sh` script now works. Probably want to specify to `pip install conan==1.59.0` in the README if the commands are not compatible with later versions.
  - `conan` initially failed with a cryptic error message. I discovered it seems to require a `node` installation. Running `brew install node` fixed this.
- OK, I need to build the binaries from scratch. Should I build the WebAssembly or native binaries?
  - I tried building the WebAssembly binaries first. The build was successful, but those ended up failing when I later went to setup griddly via `pip install`
  - Let's build the native binaries instead. That build was also successful.
- I tried to run `ctest .` but there were no tests found either in the root or in the `tests` folder. I'm just going to proceed without running these tests...

### Installing griddly Python package
- I see that `setup.py` has been replaced by `pyproject.toml` -- probably want to update the README
- Is there a Python version conflict between griddly and gym? Following the [installation section of the docs](https://griddly.readthedocs.io/en/latest/getting-started/installation/index.html), I created my conda environment with Python 3.7. However, when I `pip install` from the `griddly` repo, I get a version error, which makes sense given what's specified in the `pyproject.toml`
```
ERROR: Package 'griddly' requires a different Python: 3.7.16 not in '<3.12,>=3.8'
```
- I ended up making a new conda environment with Python 3.8, which ultimately allowed me to successfully install griddly via:
```
pip install -e .
```

### Testing griddly
- I have a `test.py` that is as follows:
```
import gymnasium as gym
import griddly

if __name__ == '__main__':

    env = gym.make('GDY-Sokoban-v0')
    env.reset()
```
- Note that I had to change the import from `gym` (what's written in the docs) to `gymnasium`
- This script no longer seg faults, but it encounters the Vulkan error shown above

This is as far as I got - do you have any suggested next steps?

**Comment by gabegrand** [comment]
Hi @Bam4d, just checking in to see if you have any pointers on how to resolve the Vulkan error encountered above? Or perhaps an ETA on shipping automated M1/M2 builds with the new github actions pipeline?

**Comment by Bam4d** [comment]
Hey @gabegrand, Sorry its taking me a while to respond!

I have a M2 mac now so I can try to debug this at the weekend.

I don't think the github actions pipelines are going to solve the problem with m1/m2 macs but I'll take a look into it to make sure there's not something Im missing.

**Comment by gabegrand** [comment]
No worries @Bam4d! Thanks for looking into this and please let me know if I can be of help.

**Comment by Bam4d** [comment]
Hey @gabegrand Been having a look at this and I have the same problem as you do on macos.

I believe that its something to do with the loader for vulkan (the graphics library) not being found.

I've installed molten-vk using brew (which is the mac vulkan layer around it's metal framework) which i belive should work but it doesnt appear to help very well annoyingly. 

I think volk (the library that loads vulkan) is trying to find the installed molten-vk but it is not finding it. I'll do some more investigating soon. 

It seems that you *can* still use Griddly but just not use any of the rendering. So for example you can set both the global observer type and player observer type to VECTOR and this will not try to load any of the graphics libraries.

**Comment by gabegrand** [comment]
Hey Chris, glad you were able to reproduce the error on your Mac. On my end, can confirm that setting both observer types to VECTOR, I was able to load Sokoban. Now if we can just get the rendering to work... :) hopefully it's just a matter of tracking down the load paths

**Comment by Bam4d** [comment]
@gabegrand I belive this is now fixed. I have it working on my M2 mac. let me know how you get on with it!

**Comment by gabegrand** [comment]
Thanks so much for pushing the patch! Unfortunately, for the moment, I'm still getting the same error. Can you let me know if I'm missing something? Here's what I just tried:
1. Install molten-vk using brew
```
brew install molten-vk
```
2. Download latest griddly develop branch 
```
git pull
```
3. Re-install the package
```
pip install -e .
```
4. Rebuild the binaries using the CMAKE presets from the README
```
# Download the build requirements
./configure.sh -b=Debug

# Configure build with preset
cmake --preset="Debug Native"

# Build with preset
cmake --build build --config Debug
```
5. Run a test script
```
env = gym.make(
    'GDY-Sokoban-v0',
)
observation, info = env.reset()
```

This produced the same Vulkan error from before. Do you see anything I missed?

**Comment by gabegrand** [comment]
Update: I tried uninstalling and reinstalling griddly from scratch, this time using the manual build. I'm still getting the same Vulkan error. @Bam4d do you have any suggestions for steps I could take to debug this? I'm quite motivated to get this working haha

**Comment by Bam4d** [comment]
1) ok, so the molten-vk from brew does not work well. You want to install the [official SDK](https://vulkan.lunarg.com/sdk/home#mac)

2) You need to build everything first. Before the python install. The python install ( now using poetry, see 3 ) will copy the python_griddly module to a place where it can be seen by your python env. This might be why you are seeing the error in #291.

3) The stuff on develop branch uses poetry as an alternative to conda/venv (not documented yet) but instead of using pip/pip install you should:

```
pip install poetry
cd python
poetry install
```
(this sets up a virtual environment for you and installs the built binaries in the right places)

Let me know if you get stuck again. Happy to help debug.

**Comment by gabegrand** [comment]
Thanks so much! I'm still suck with the poetry install -- moving that discussion to https://github.com/Bam4d/Griddly/issues/291

As for the Vulkan install, I uninstalled the molten-vk from brew and installed the official SDK for MacOS. (I also had to manually add `source /path/to/VulkanSDK/1.x.xxx.x/setup-env.sh` to my `.zshrc` file to make sure the `VULKAN_SDK` environment variable was being properly set.) 

After this installation, I'm no longer getting `[error] BAD VK Result-3` and can pass other rendering options besides `VECTOR`! However, the renders appear to be screwed up:

SPRITE_2D
<img width="424" alt="SPRITE_2D" src="https://github.com/Bam4d/Griddly/assets/10052880/0e021287-f40c-487c-92f1-94226fe32f29">

BLOCK_2D
<img width="424" alt="BLOCK_2D" src="https://github.com/Bam4d/Griddly/assets/10052880/ddcf90b0-48c9-4092-9749-31240e8c2512">

Do you know what could be causing this?

Running `vkvia` shows that everything appears to be normal:
```
VIA_INFO:    SDK Found! - Will attempt to run tests
VIA_INFO:       Attempting to run ./vkcube in /Applications/vkcube.app/Contents/MacOS
VIA_INFO:           Command-line: ./vkcube --c 100 --suppress_popups
Selected GPU 0: Apple M1 Max, type: IntegratedGpu
VIA_INFO:           Command-line: ./vkcube --c 100 --suppress_popups --validate
Selected GPU 0: Apple M1 Max, type: IntegratedGpu
SUCCESS: Vulkan analysis completed properly using Vulkan 1.2
```

**Comment by gabegrand** [comment]
(FYI: I am also still stuck on https://github.com/Bam4d/Griddly/issues/291, but I'm able to produce this using an older `griddly` conda environment that I had created a few weeks ago. Presumably that was before the switch to the poetry install.)

**Comment by Bam4d** [comment]
hmm, those images look super garbled haha! Not sure what could possibly be going on there.

I'm testing/developing on an M2 Mac but i'm not sure why it would be any different.

the "python_griddly" not found error will be either because the install has built a version of griddly using the wrong python version or because it has not built at all.

after running `poetry install` you should be able to see the `python_griddly.XXXXX.so` in `python/griddly/libs` folder. 
If its not there either a) it did not build or b) the `poetry install` did not succeed for some reason. (make sure you run the poetry install from the python folder

If it is there....does it have the correct python version (the same one you are running with)?
